#!/usr/bin/env python
import csv

from generation import generation

if __name__ == '__main__':
  with open('out.csv', 'wb') as f:
    w = csv.writer(f, delimiter=';', quotechar='|', quoting=csv.QUOTE_MINIMAL)
    for i in xrange(50):
      x = generation()
      w.writerow([col[j] for j in xrange(9) for col in x[0]])
